use std::fs;
use std::io::Write;
use std::path::{Path, PathBuf};

use clap::Args;

/// The core philosophical content for AGENTS.md.
pub const AGENTS_CONTENT: &str = r#"## Issue Tracking

**bd** is infrastructure for you, the agent. It's your external memory.

A bead is a **promise**: you WILL get to this, just not now. When you're in the middle of something and notice tech debt, bugs, slop, or follow-on work that's out of scope—file a bead. Capture enough context that anyone (including future-you) can pick it up cold. Then keep going.

```bash
bd ready              # What can I work on?
bd create "..."       # Promise to handle this later
bd claim <id>         # I'm on it
bd close <id>         # Done
```

Run `bd prime` for full workflow."#;

#[derive(Args, Debug)]
pub struct OnboardArgs {
    /// Generate BD_GUIDE.md at the specified path instead of printing instructions.
    #[arg(long, value_name = "PATH")]
    pub output: Option<PathBuf>,
}

pub fn render_instructions(initialized: bool) {
    let mut stdout = std::io::stdout().lock();

    let _ = writeln!(stdout, "\n\x1b[1mbd Onboarding\x1b[0m\n");

    if initialized {
        let _ = writeln!(stdout, "\x1b[32m✓ beads initialized\x1b[0m\n");
    }

    let _ = writeln!(stdout, "\x1b[33mAdd the following to AGENTS.md:\x1b[0m\n");

    let _ = writeln!(stdout, "\x1b[36m--- BEGIN AGENTS.MD CONTENT ---\x1b[0m");
    let _ = writeln!(stdout, "{AGENTS_CONTENT}");
    let _ = writeln!(stdout, "\x1b[36m--- END AGENTS.MD CONTENT ---\x1b[0m\n");

    let _ = writeln!(stdout, "\x1b[1mIf CLAUDE.md exists:\x1b[0m");
    let _ = writeln!(
        stdout,
        "  Add a note referencing AGENTS.md for bd workflow.\n"
    );

    let _ = writeln!(
        stdout,
        "\x1b[32mWhen done: \"bd onboarding complete\"\x1b[0m\n"
    );
}

pub fn generate_guide(path: &Path) {
    let version = env!("CARGO_PKG_VERSION");

    let content = format!(
        r#"<!-- Auto-generated by bd v{version} - DO NOT EDIT MANUALLY -->
<!-- Run 'bd onboard --output <path>' to regenerate -->

# BD (Beads) Guide

This file contains bd workflow guidance for AI agents.
It is auto-generated and version-stamped.

> For project-specific instructions, see AGENTS.md in the repository root.

---

{AGENTS_CONTENT}

---

**Generated by bd v{version}**

To regenerate after upgrading bd:
```bash
bd onboard --output {path}
```
"#,
        path = path.display()
    );

    if let Some(parent) = path.parent()
        && !parent.as_os_str().is_empty()
        && !parent.exists()
    {
        let _ = fs::create_dir_all(parent);
    }

    let _ = fs::write(path, content);
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn agents_content_has_key_elements() {
        assert!(AGENTS_CONTENT.contains("bd ready"));
        assert!(AGENTS_CONTENT.contains("bd create"));
        assert!(AGENTS_CONTENT.contains("bd prime"));
        assert!(AGENTS_CONTENT.contains("promise"));
        assert!(AGENTS_CONTENT.contains("external memory"));
    }
}
