//! Cohere North / Command A 2026 response parser.
//!
//! **Upstream:** `model/parsers/cohere.go` (ollama, MIT, Copyright (c) Ollama).
//! Ported against `4713800b08b2ddf5e14acf8398953cf7b12f169b` (2026-07-28).
//!
//! ## The shape of a Cohere turn
//!
//! Upstream's own note, kept because it is the load-bearing fact: the
//! **generation prompt already ends with `<|START_THINKING|>`** (reasoning on)
//! or `<|START_THINKING|><|END_THINKING|>` (reasoning off). So the model's first
//! generated byte is already *inside* the thinking block, and this parser never
//! looks for an opening thinking tag at all.
//!
//! After thinking, the model emits one of:
//!
//! ```text
//! <|START_TEXT|>the reply<|END_TEXT|><|END_OF_TURN_TOKEN|>
//! <|START_ACTION|>[{"tool_call_id":"0","tool_name":"f","parameters":{}}]<|END_ACTION|>
//! ```
//!
//! ## Three real-world messes this parser absorbs
//!
//! 1. **Legacy markers.** `<|START_RESPONSE|>` / `<|END_RESPONSE|>` are from the
//!    older Command A chat template, which still ships in these models'
//!    `tokenizer_config` and therefore still turns up in sampled output. Treated
//!    as exact aliases of `START_TEXT` / `END_TEXT`.
//! 2. **Missing wrappers.** Models sometimes skip `<|START_TEXT|>` entirely and
//!    just start talking, or close with `<|END_OF_TURN_TOKEN|>` instead of
//!    `<|END_TEXT|>`. Both are handled rather than treated as errors.
//! 3. **Malformed action JSON.** See [`parse_actions`] -- one bad tool call must
//!    not take its well-formed siblings down with it.
//!
//! ## The hang this parser was fixed for -- do not undo it
//!
//! Between blocks ([`State::AwaitingBlock`]) it is tempting to buffer until a
//! recognised opener shows up. That is exactly what upstream used to do, and it
//! **buffered forever** when the model emitted an unrecognised tag like
//! `<|TOOL_PLAN|>`, presenting to the user as a hung response. The rule now is:
//! wait **only** while the buffer is still a proper prefix of a tag we know
//! ([`maybe_partial_tag`]); anything else streams out as content immediately.
//! Upstream pins this with `TestCohereParseStreamsBeforeDone`, and so do we.

use serde::Deserialize;

use crate::api::{Message, ThinkValue, Tool, ToolCall, ToolCallArguments, ToolCallFunction};

use super::{Parsed, Parser, ParserError, overlap, trailing_whitespace_len};

/// **Upstream:** the `cohere*` tag consts. These are the model's special tokens.
const END_THINKING: &str = "<|END_THINKING|>";
const START_THINKING: &str = "<|START_THINKING|>";
const START_TEXT: &str = "<|START_TEXT|>";
const END_TEXT: &str = "<|END_TEXT|>";
const START_ACTION: &str = "<|START_ACTION|>";
const END_ACTION: &str = "<|END_ACTION|>";
const END_OF_TURN: &str = "<|END_OF_TURN_TOKEN|>";

/// Legacy markers from the older Command A chat template. **Upstream:**
/// `cohereStartResponse` / `cohereEndResponse`, with the comment explaining they
/// still ship in these models' `tokenizer_config` and still get sampled.
const START_RESPONSE: &str = "<|START_RESPONSE|>";
const END_RESPONSE: &str = "<|END_RESPONSE|>";

/// **Upstream:** `cohereParserState`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
enum State {
    #[default]
    CollectingThinking,
    /// Between blocks -- looking for the next opener. See the module docs on why
    /// this state must never buffer indefinitely.
    AwaitingBlock,
    CollectingContent,
    CollectingAction,
}

/// **Upstream:** `CohereParser`.
#[derive(Debug, Default)]
pub struct CohereParser {
    state: State,
    buffer: String,
    /// Running counter across the generation, same as olmo3's.
    call_index: usize,
}

impl CohereParser {
    /// **Upstream:** `(*CohereParser).eat`.
    ///
    /// Returns `(content, thinking, calls, more)`. `more = true` means a state
    /// transition happened and the rest of the buffer should be reprocessed --
    /// one chunk can carry a whole `thinking + text` pair.
    fn eat(&mut self, done: bool) -> (String, String, Vec<ToolCall>, bool) {
        if self.buffer.is_empty() {
            return (String::new(), String::new(), Vec::new(), false);
        }

        match self.state {
            State::CollectingThinking => {
                if let Some(idx) = self.buffer.find(END_THINKING) {
                    let thinking = self.buffer[..idx].trim_end().to_string();
                    self.buffer = self.buffer[idx + END_THINKING.len()..].to_string();
                    self.state = State::AwaitingBlock;
                    return (String::new(), thinking, Vec::new(), true);
                }

                // Hold back a possible partial `<|END_THINKING|>` AND the
                // whitespace in front of it -- if the tag does land, that
                // whitespace gets trimmed, and an emitted byte cannot be
                // un-emitted.
                let keep = overlap(&self.buffer, END_THINKING);
                let mut emit_end = self.buffer.len() - keep;
                let (head, _) = super::chop(&self.buffer, emit_end);
                emit_end -= trailing_whitespace_len(head);

                let mut thinking = String::new();
                if emit_end > 0 {
                    let (out, rest) = super::chop(&self.buffer, emit_end);
                    thinking = out.to_string();
                    self.buffer = rest.to_string();
                }
                (String::new(), thinking, Vec::new(), false)
            }

            State::AwaitingBlock => {
                // Order matters and is upstream's: START_TEXT is looked for
                // across the WHOLE buffer before START_RESPONSE is considered
                // at all. Anything in front of the opener is discarded.
                for open in [START_TEXT, START_RESPONSE] {
                    if let Some(idx) = self.buffer.find(open) {
                        self.buffer = self.buffer[idx + open.len()..].to_string();
                        self.state = State::CollectingContent;
                        return (String::new(), String::new(), Vec::new(), true);
                    }
                }
                if let Some(idx) = self.buffer.find(START_ACTION) {
                    self.buffer = self.buffer[idx + START_ACTION.len()..].to_string();
                    self.state = State::CollectingAction;
                    return (String::new(), String::new(), Vec::new(), true);
                }

                let trimmed = self.buffer.trim_start().to_string();

                // A bare end-of-turn marker between blocks is CONSUMED, not
                // shown -- it is framing, and leaking it puts `<|END_OF_TURN_TOKEN|>`
                // in front of the user.
                if let Some(rest) = trimmed.strip_prefix(END_OF_TURN) {
                    self.buffer = rest.to_string();
                    return (String::new(), String::new(), Vec::new(), true);
                }

                if trimmed.is_empty() {
                    if done {
                        self.buffer.clear();
                    }
                    return (String::new(), String::new(), Vec::new(), false);
                }

                // THE ANTI-HANG RULE. Wait only while this could still grow into
                // a tag we recognise; otherwise treat it as content and stream
                // it now. See the module docs.
                if !done && maybe_partial_tag(&trimmed) {
                    return (String::new(), String::new(), Vec::new(), false);
                }

                self.buffer = trimmed;
                self.state = State::CollectingContent;
                (String::new(), String::new(), Vec::new(), true)
            }

            State::CollectingContent => {
                // END_OF_TURN closes content too, for models that skip END_TEXT.
                for close in [END_TEXT, END_RESPONSE, END_OF_TURN] {
                    if let Some(idx) = self.buffer.find(close) {
                        let content = self.buffer[..idx].to_string();
                        self.buffer = self.buffer[idx + close.len()..].to_string();
                        self.state = State::AwaitingBlock;
                        return (content, String::new(), Vec::new(), true);
                    }
                }

                let keep = overlap(&self.buffer, END_TEXT)
                    .max(overlap(&self.buffer, END_RESPONSE))
                    .max(overlap(&self.buffer, END_OF_TURN));
                let emit_end = self.buffer.len() - keep;

                // NOTE: no trailing-whitespace widening here, unlike the
                // thinking branch above. Content whitespace in front of
                // `<|END_TEXT|>` is the user's text, not framing, so eating it
                // would drop a real space from the reply.
                let mut content = String::new();
                if emit_end > 0 {
                    let (out, rest) = super::chop(&self.buffer, emit_end);
                    content = out.to_string();
                    self.buffer = rest.to_string();
                }
                if done && !self.buffer.is_empty() {
                    // Stream ended mid-partial-tag. It was never a tag, so it is
                    // content -- release it rather than swallowing it.
                    content.push_str(&self.buffer);
                    self.buffer.clear();
                }
                (content, String::new(), Vec::new(), false)
            }

            State::CollectingAction => {
                if let Some(idx) = self.buffer.find(END_ACTION) {
                    let payload = self.buffer[..idx].to_string();
                    self.buffer = self.buffer[idx + END_ACTION.len()..].to_string();
                    self.state = State::AwaitingBlock;
                    return (String::new(), String::new(), parse_actions(&payload), true);
                }
                if done {
                    // Best effort on truncated output: a `[` with two complete
                    // objects and no closing `]` still yields two usable calls
                    // via the object-scanning fallback.
                    let payload = std::mem::take(&mut self.buffer);
                    return (String::new(), String::new(), parse_actions(&payload), false);
                }
                // A half-written JSON array is not parseable, so there is
                // nothing to emit early. Wait.
                (String::new(), String::new(), Vec::new(), false)
            }
        }
    }
}

impl Parser for CohereParser {
    /// **Upstream:** `(*CohereParser).Init`.
    ///
    /// Three-way opening state, and the precedence is upstream's:
    ///
    /// 1. **assistant prefill with content wins outright** -- the prompt left an
    ///    open `<|START_TEXT|>` for the model to continue, so we are already
    ///    inside a content block. Note this beats `thinking_enabled`: even with
    ///    thinking on, a prefill means thinking is over.
    /// 2. thinking enabled -> [`State::CollectingThinking`].
    /// 3. otherwise -> [`State::AwaitingBlock`] (the prompt closed thinking for
    ///    us with `<|START_THINKING|><|END_THINKING|>`).
    ///
    /// `None` for `think` means **on**, because this family's template enables
    /// reasoning by default. That is a per-family choice, not a global one.
    fn init(
        &mut self,
        tools: Vec<Tool>,
        last_message: Option<&Message>,
        think: Option<&ThinkValue>,
    ) -> Vec<Tool> {
        self.buffer.clear();
        self.call_index = 0;

        let thinking_enabled = think.is_none_or(|t| t.enabled());
        let assistant_prefill =
            last_message.is_some_and(|m| m.role == "assistant" && !m.content.is_empty());

        self.state = if assistant_prefill {
            State::CollectingContent
        } else if thinking_enabled {
            State::CollectingThinking
        } else {
            State::AwaitingBlock
        };

        tools
    }

    /// **Upstream:** `(*CohereParser).Add`.
    fn add(&mut self, s: &str, done: bool) -> Result<Parsed, ParserError> {
        self.buffer.push_str(s);

        let mut out = Parsed::default();
        loop {
            let (content, thinking, calls, more) = self.eat(done);
            out.content.push_str(&content);
            out.thinking.push_str(&thinking);
            out.calls.extend(calls);
            if !more {
                break;
            }
        }

        for call in &mut out.calls {
            call.function.index = self.call_index;
            self.call_index += 1;
        }

        Ok(out)
    }

    fn preserved_tokens(&self) -> Vec<&'static str> {
        vec![
            START_THINKING,
            END_THINKING,
            START_TEXT,
            END_TEXT,
            START_ACTION,
            END_ACTION,
            START_RESPONSE,
            END_RESPONSE,
        ]
    }

    fn has_tool_support(&self) -> bool {
        true
    }

    fn has_thinking_support(&self) -> bool {
        true
    }
}

/// Is `s` a **proper** prefix of one of the openers we wait for?
///
/// **Upstream:** `maybePartialTag`. Note `len(s) < len(tag)` -- a *complete* tag
/// is not "partial", it is a match, and the caller has already handled it.
///
/// This function is the entire anti-hang mechanism. Widen the tag list and you
/// widen how long the parser will sit silent; drop the length check and a
/// complete tag stalls forever.
fn maybe_partial_tag(s: &str) -> bool {
    [START_TEXT, START_RESPONSE, START_ACTION, END_OF_TURN]
        .iter()
        .any(|tag| s.len() < tag.len() && tag.starts_with(s))
}

/// One entry of a Cohere action array. **Upstream:** `cohereToolCall`.
#[derive(Debug, Default, Deserialize)]
struct CohereToolCall {
    #[serde(default)]
    tool_call_id: String,
    #[serde(default)]
    tool_name: String,
    #[serde(default)]
    parameters: ToolCallArguments,
}

impl From<CohereToolCall> for ToolCall {
    fn from(c: CohereToolCall) -> Self {
        ToolCall {
            id: c.tool_call_id,
            function: ToolCallFunction {
                name: c.tool_name,
                arguments: c.parameters,
                ..Default::default()
            },
        }
    }
}

/// Parse the JSON array inside an action block.
///
/// **Upstream:** `parseCohereActions`, and this is a **two-pass recovery**, not
/// a plain `serde_json::from_str`:
///
/// 1. Try the whole array. Normal path, done.
/// 2. If that fails, fall back to [`scan_json_objects`] -- pull out the balanced
///    top-level `{...}` chunks and parse each one **independently**.
///
/// Why pass 2 exists, from upstream's comment: sampled output occasionally
/// malforms the JSON -- a missing comma between calls, an unquoted value like
/// `{"time": 15:30}`. Without the fallback, ONE bad call drops every sibling in
/// the array, so a reply that asked for `set_alarm` and `get_weather` loses both
/// because of the alarm. With it, the good ones survive and the bad one is
/// skipped (upstream logs a warning; we have no logger, so it is silently
/// dropped -- same observable behaviour).
///
/// Returns no calls for unparseable garbage. Never fails the generation.
fn parse_actions(payload: &str) -> Vec<ToolCall> {
    let payload = payload.trim();
    if payload.is_empty() {
        return Vec::new();
    }

    if let Ok(parsed) = serde_json::from_str::<Vec<CohereToolCall>>(payload) {
        return parsed.into_iter().map(ToolCall::from).collect();
    }

    scan_json_objects(payload)
        .into_iter()
        .filter_map(|obj| serde_json::from_str::<CohereToolCall>(&obj).ok())
        .map(ToolCall::from)
        .collect()
}

/// Pull the balanced top-level `{...}` chunks out of `s`.
///
/// **Upstream:** `scanJSONObjects`. It tracks string state and escapes, which is
/// the whole point: a value like `{"x": "{not json}"}` contains braces **inside a
/// string**, and a naive brace counter splits it into nonsense. Upstream pins
/// that exact case.
///
/// **Divergence, and why it is safe:** upstream indexes raw bytes; we walk
/// `char_indices`. Every character it treats specially (`\`, `"`, `{`, `}`) is
/// ASCII, and a UTF-8 continuation byte can never equal an ASCII byte, so both
/// see exactly the same delimiters. Using char boundaries means the slices this
/// returns can never split a multi-byte character.
fn scan_json_objects(s: &str) -> Vec<String> {
    let mut objects = Vec::new();
    let mut depth: i32 = 0;
    let mut start: Option<usize> = None;
    let mut in_string = false;
    let mut escaped = false;

    for (i, c) in s.char_indices() {
        if escaped {
            escaped = false;
        } else if c == '\\' && in_string {
            escaped = true;
        } else if c == '"' {
            in_string = !in_string;
        } else if in_string {
            // Inside a string: braces are data, not structure. Skip.
        } else if c == '{' {
            if depth == 0 {
                start = Some(i);
            }
            depth += 1;
        } else if c == '}' && depth > 0 {
            depth -= 1;
            if depth == 0
                && let Some(st) = start.take()
            {
                objects.push(s[st..i + c.len_utf8()].to_string());
            }
        }
    }

    objects
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    /// Upstream's `cohereAddAll` helper: feed the chunks, `done` on the last.
    fn add_all(p: &mut CohereParser, chunks: &[&str]) -> Parsed {
        let mut out = Parsed::default();
        for (i, c) in chunks.iter().enumerate() {
            let got = p.add(c, i == chunks.len() - 1).expect("add");
            out.content.push_str(&got.content);
            out.thinking.push_str(&got.thinking);
            out.calls.extend(got.calls);
        }
        out
    }

    fn cohere() -> CohereParser {
        let mut p = CohereParser::default();
        p.init(Vec::new(), None, None);
        p
    }

    /// Upstream `TestCohereParseThinkingThenText`.
    #[test]
    fn thinking_runs_until_the_end_thinking_tag_then_text_takes_over() {
        let mut p = cohere();
        let got = add_all(
            &mut p,
            &[
                "Let me think",
                " about this.<|END_THINKING|>",
                "<|START_TEXT|>Hello",
                " world!<|END_TEXT|>",
            ],
        );
        assert_eq!(got.thinking, "Let me think about this.");
        assert_eq!(got.content, "Hello world!");
        assert!(got.calls.is_empty());
    }

    /// Upstream `TestCohereParseSplitTags` -- every tag split across a chunk
    /// boundary, none of it allowed to leak.
    #[test]
    fn tags_split_across_chunk_boundaries_never_leak_into_output() {
        let mut p = cohere();
        let got = add_all(
            &mut p,
            &["think<|END_TH", "INKING|><|STAR", "T_TEXT|>ans", "wer<|END_", "TEXT|>"],
        );
        assert_eq!(got.thinking, "think");
        assert_eq!(got.content, "answer");
    }

    /// Upstream `TestCohereParseToolCall`.
    #[test]
    fn an_action_block_yields_indexed_tool_calls() {
        let mut p = cohere();
        let got = add_all(
            &mut p,
            &[
                "plan<|END_THINKING|><|START_ACTION|>[\n",
                r#"    {"tool_call_id": "0", "tool_name": "get_weather", "parameters": {"city": "Paris"}},"#,
                r#"    {"tool_call_id": "1", "tool_name": "get_time", "parameters": {}}"#,
                "\n]<|END_ACTION|>",
            ],
        );
        assert_eq!(got.thinking, "plan");
        assert!(got.content.is_empty());
        assert_eq!(got.calls.len(), 2);
        assert_eq!(got.calls[0].function.name, "get_weather");
        assert_eq!(got.calls[1].function.name, "get_time");
        assert_eq!(got.calls[0].function.arguments.get("city"), Some(&json!("Paris")));
        assert_eq!(got.calls[0].function.index, 0);
        assert_eq!(got.calls[1].function.index, 1);
        // The wire `tool_call_id` is carried through, not invented.
        assert_eq!(got.calls[0].id, "0");
        assert_eq!(got.calls[1].id, "1");
    }

    /// Upstream `TestCohereParseReasoningOff`. With reasoning off the prompt
    /// already closed thinking, so the stream starts between blocks.
    #[test]
    fn with_reasoning_off_the_stream_starts_between_blocks() {
        let mut p = CohereParser::default();
        p.init(Vec::new(), None, Some(&ThinkValue::Bool(false)));
        let got = add_all(&mut p, &["<|START_TEXT|>direct answer<|END_TEXT|>"]);
        assert!(got.thinking.is_empty());
        assert_eq!(got.content, "direct answer");
    }

    /// `None` means ON for this family -- its template enables reasoning.
    #[test]
    fn an_unspecified_think_value_defaults_to_reasoning_on() {
        let mut p = CohereParser::default();
        p.init(Vec::new(), None, None);
        let got = add_all(&mut p, &["reasoning<|END_THINKING|><|START_TEXT|>hi<|END_TEXT|>"]);
        assert_eq!(got.thinking, "reasoning");
        assert_eq!(got.content, "hi");
    }

    /// Upstream `TestCohereParseBareContent` -- the model skipped the
    /// `<|START_TEXT|>` wrapper entirely.
    #[test]
    fn raw_text_after_thinking_is_treated_as_content() {
        let mut p = cohere();
        let got = add_all(
            &mut p,
            &["thought<|END_THINKING|>", "Just plain text", " output"],
        );
        assert_eq!(got.thinking, "thought");
        assert_eq!(got.content, "Just plain text output");
    }

    /// Upstream `TestCohereParseEndOfTurnWithoutEndText`.
    #[test]
    fn end_of_turn_closes_content_for_models_that_skip_end_text() {
        let mut p = cohere();
        let got = add_all(
            &mut p,
            &["t<|END_THINKING|><|START_TEXT|>answer<|END_OF_TURN_TOKEN|>"],
        );
        assert_eq!(got.content, "answer");
    }

    /// Upstream `TestCohereParseEndOfTurnBetweenBlocks` -- the marker is
    /// consumed as framing, never shown to the user.
    #[test]
    fn a_bare_end_of_turn_marker_between_blocks_is_swallowed() {
        let mut p = cohere();
        let got = add_all(
            &mut p,
            &["t<|END_THINKING|><|START_TEXT|>hi<|END_TEXT|><|END_OF_TURN_TOKEN|>"],
        );
        assert_eq!(got.thinking, "t");
        assert_eq!(got.content, "hi");
    }

    /// Upstream `TestCohereParseBareContentBeforeEndOfTurn`.
    #[test]
    fn bare_content_followed_by_end_of_turn_keeps_the_content() {
        let mut p = cohere();
        let got = add_all(&mut p, &["t<|END_THINKING|>plain answer<|END_OF_TURN_TOKEN|>"]);
        assert_eq!(got.content, "plain answer");
    }

    /// Upstream `TestCohereParsePrefillContinuation` -- a prefill beats
    /// reasoning-on and drops us straight into content.
    #[test]
    fn an_assistant_prefill_continues_an_already_open_text_block() {
        let mut p = CohereParser::default();
        let last = Message::new("assistant", "partial");
        p.init(Vec::new(), Some(&last), None);
        let got = add_all(&mut p, &[" continued<|END_TEXT|>"]);
        assert!(got.thinking.is_empty());
        assert_eq!(got.content, " continued");
    }

    /// Upstream `TestCohereParseLegacyResponseMarkers`.
    #[test]
    fn the_legacy_response_markers_work_exactly_like_the_text_ones() {
        let mut p = cohere();
        let got = add_all(
            &mut p,
            &["plan<|END_THINKING|>", "<|START_RESPONSE|>Hello", " there<|END_RESPONSE|>"],
        );
        assert_eq!(got.thinking, "plan");
        assert_eq!(got.content, "Hello there");
    }

    /// Upstream `TestCohereParseStreamsBeforeDone`. This is the **hang
    /// regression**: output after `END_THINKING` that opens with an
    /// unrecognised tag must stream as it arrives, not buffer until the
    /// generation finishes.
    #[test]
    fn unrecognised_output_between_blocks_streams_instead_of_hanging() {
        for chunk in [
            "<|START_RESPONSE|>The answer is 42.",
            "<|TOOL_PLAN|>I should call the tool.",
            "Just plain text.",
        ] {
            let mut p = cohere();
            p.add("x<|END_THINKING|>", false).expect("add");
            // done = false -- still streaming. Content MUST come out anyway.
            let got = p.add(chunk, false).expect("add");
            assert!(!got.content.is_empty(), "buffered instead of streaming: {chunk:?}");
        }
    }

    /// Upstream `TestCohereParseMalformedActions`: one bad call must not drop
    /// its well-formed sibling.
    #[test]
    fn a_malformed_action_does_not_take_its_siblings_down_with_it() {
        let mut p = cohere();
        let got = add_all(
            &mut p,
            &[
                "plan<|END_THINKING|><|START_ACTION|>[\n",
                r#"    {"tool_call_id": "0", "tool_name": "set_alarm", "parameters": {"time": 15:30}},"#,
                r#"    {"tool_call_id": "1", "tool_name": "get_weather", "parameters": {"city": "Oslo"}}"#,
                "\n]<|END_ACTION|>",
            ],
        );
        assert_eq!(got.calls.len(), 1);
        assert_eq!(got.calls[0].function.name, "get_weather");
    }

    /// Missing comma between two objects -- both must survive, and braces
    /// inside a string value must not split an object.
    #[test]
    fn a_missing_comma_between_actions_still_yields_both_calls() {
        let mut p = cohere();
        let got = add_all(
            &mut p,
            &[
                "<|END_THINKING|><|START_ACTION|>[",
                r#"{"tool_call_id": "0", "tool_name": "a", "parameters": {}}"#,
                r#"{"tool_call_id": "1", "tool_name": "b", "parameters": {"x": "{not json}"}}"#,
                "]<|END_ACTION|>",
            ],
        );
        assert_eq!(got.calls.len(), 2);
        assert_eq!(got.calls[0].function.name, "a");
        assert_eq!(got.calls[1].function.name, "b");
        assert_eq!(
            got.calls[1].function.arguments.get("x"),
            Some(&json!("{not json}")),
            "braces inside a string value must not split objects"
        );
    }

    #[test]
    fn unparseable_action_garbage_yields_no_calls_and_no_error() {
        let mut p = cohere();
        let got = add_all(&mut p, &["x<|END_THINKING|><|START_ACTION|>[!!!]<|END_ACTION|>"]);
        assert!(got.calls.is_empty());
    }

    /// A truncated action block (no `<|END_ACTION|>`) still yields what it can
    /// on `done` -- best effort, upstream's words.
    #[test]
    fn a_truncated_action_block_still_yields_its_complete_calls_on_done() {
        let mut p = cohere();
        let got = add_all(
            &mut p,
            &[
                "<|END_THINKING|><|START_ACTION|>[",
                r#"{"tool_call_id": "0", "tool_name": "f", "parameters": {"a": 1}}"#,
            ],
        );
        assert_eq!(got.calls.len(), 1);
        assert_eq!(got.calls[0].function.name, "f");
    }

    /// One byte at a time must agree with one big chunk.
    #[test]
    fn feeding_one_byte_at_a_time_gives_the_same_answer_as_one_big_chunk() {
        let input = "reasoning here<|END_THINKING|><|START_TEXT|>The answer lah.<|END_TEXT|>";

        let mut whole = cohere();
        let want = add_all(&mut whole, &[input]);

        let mut p = cohere();
        let mut got = Parsed::default();
        for (i, ch) in input.char_indices() {
            let part = p
                .add(&input[i..i + ch.len_utf8()], i + ch.len_utf8() == input.len())
                .expect("add");
            got.content.push_str(&part.content);
            got.thinking.push_str(&part.thinking);
            got.calls.extend(part.calls);
        }

        assert_eq!(got.thinking, want.thinking);
        assert_eq!(got.content, want.content);
        assert_eq!(got.thinking, "reasoning here");
        assert_eq!(got.content, "The answer lah.");
    }

    #[test]
    fn arguments_keep_the_order_the_model_wrote_them() {
        let mut p = cohere();
        let got = add_all(
            &mut p,
            &[r#"<|END_THINKING|><|START_ACTION|>[{"tool_call_id":"0","tool_name":"f","parameters":{"zebra":1,"apple":2}}]<|END_ACTION|>"#],
        );
        let keys: Vec<&str> = got.calls[0]
            .function
            .arguments
            .0
            .keys()
            .map(String::as_str)
            .collect();
        assert_eq!(keys, ["zebra", "apple"]);
    }

    #[test]
    fn maybe_partial_tag_only_says_yes_to_a_proper_prefix() {
        assert!(maybe_partial_tag("<|STAR"));
        assert!(maybe_partial_tag("<"));
        // A COMPLETE tag is not partial -- the caller already matched it, and
        // calling it partial here is how the parser hangs.
        assert!(!maybe_partial_tag(START_TEXT));
        assert!(!maybe_partial_tag("Just plain text."));
        assert!(!maybe_partial_tag("<|TOOL_PLAN|>"));
    }

    /// Upstream `TestCohereParserRegistered`.
    #[test]
    fn cohere_advertises_its_tags_and_supports_both_tools_and_thinking() {
        let p = parser_for_name_cohere();
        assert!(p.has_tool_support());
        assert!(p.has_thinking_support());
        for tok in [START_THINKING, END_THINKING, START_TEXT, END_TEXT, START_ACTION, END_ACTION, START_RESPONSE, END_RESPONSE] {
            assert!(p.preserved_tokens().contains(&tok), "missing {tok}");
        }
    }

    fn parser_for_name_cohere() -> Box<dyn Parser> {
        super::super::parser_for_name("cohere").expect("cohere must be registered")
    }
}
