//! Olmo 3 -- two parsers, one family.
//!
//! **Upstream:** `model/parsers/olmo3.go` and `model/parsers/olmo3_think.go`
//! (ollama, MIT, Copyright (c) Ollama). Ported against
//! `4713800b08b2ddf5e14acf8398953cf7b12f169b` (2026-07-28).
//!
//! | parser name | struct | tools | thinking |
//! |---|---|---|---|
//! | `olmo3` | [`Olmo3Parser`] | yes | no |
//! | `olmo3-think` | [`Olmo3ThinkParser`] | no | yes |
//!
//! They are genuinely separate upstream -- not one struct with flags -- because
//! they share no state machine at all. Kept separate here for the same reason.
//!
//! ## Olmo 3 calls tools in Python, not JSON
//!
//! This is the interesting bit and the reason this file is long:
//!
//! ```text
//! <function_calls>get_weather(location="San Francisco", units='metric')
//! get_time(timezone="PST")</function_calls>
//! ```
//!
//! One call per line, Python call syntax, Python literals -- `True`/`true`,
//! `None`/`null`/`nil`, single **or** double quotes, `[...]` lists and `{...}`
//! dicts. So there is a small recursive-descent literal parser at the bottom of
//! this file. It is upstream's, warts included.
//!
//! **What would make this wrong:** reaching for `serde_json` on that body. It is
//! *not* JSON -- `location="SF"` uses `=` not `:`, `True` is capitalised, keys
//! are bare, and strings may be single-quoted. Feeding it to a JSON parser fails
//! on every single real tool call.
//!
//! ## The `done` contract here is unusual, hor -- read this before using it
//!
//! [`Olmo3Parser::add`] with `done = true` **does not parse anything**. It
//! drains the buffer and returns it as content (only if it is still in the
//! content state), and that is all -- upstream returns before `parseEvents` is
//! ever reached.
//!
//! So the caller MUST feed real chunks with `done = false` and use the final
//! `add("", true)` purely as a drain. Handing the whole response in one
//! `add(everything, true)` returns the raw string, `<function_calls>` markup and
//! all, and finds zero tool calls. Upstream's own tests are written exactly that
//! way (`Add(input, false)` then `Add("", true)`), which is how we know it is
//! intended and not an accident.

use crate::api::{Message, ThinkValue, Tool, ToolCall, ToolCallArguments, ToolCallFunction};

use super::{Parsed, Parser, ParserError, overlap, trailing_whitespace_len};

/// **Upstream:** `olmo3FuncCallsOpenTag` / `olmo3FuncCallsCloseTag`.
const FUNC_CALLS_OPEN_TAG: &str = "<function_calls>";
const FUNC_CALLS_CLOSE_TAG: &str = "</function_calls>";

/// **Upstream:** `olmo3ThinkCloseTag`. Note there is no *open* tag: the prompt
/// injects `<think>` itself, so the model's very first generated byte is already
/// inside the thinking block.
const THINK_CLOSE_TAG: &str = "</think>";

// ===========================================================================
// olmo3 -- tool calls, no thinking.
// ===========================================================================

/// **Upstream:** `olmo3ParserState`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
enum State {
    #[default]
    Content,
    ToolCalls,
    /// One-shot state right after `</function_calls>`: dump whatever trails and
    /// go back to [`State::Content`]. Upstream keeps it as its own state rather
    /// than falling straight back, and the difference is observable -- the
    /// trailing text is emitted **without** any partial-open-tag buffering on
    /// that one pass.
    ToolCallsDone,
}

/// **Upstream:** `olmo3ParserEvent`.
#[derive(Debug, Clone, PartialEq)]
enum Event {
    Content(String),
    ToolCalls(Vec<ToolCall>),
}

/// The `olmo3` parser. **Upstream:** `Olmo3Parser`.
#[derive(Debug, Default)]
pub struct Olmo3Parser {
    state: State,
    buffer: String,
    /// Running counter across the whole generation, so parallel calls come back
    /// numbered 0, 1, 2, ... **Upstream:** `callIndex`. It is a *stream*
    /// counter, not a per-chunk one -- resetting it per chunk would make two
    /// calls in two chunks both claim index 0.
    call_index: usize,
}

impl Olmo3Parser {
    /// **Upstream:** `(*Olmo3Parser).parseEvents`.
    fn parse_events(&mut self) -> Vec<Event> {
        let mut all = Vec::new();
        let mut keep_looping = true;
        while keep_looping {
            let (events, again) = self.eat();
            keep_looping = again;
            all.extend(events);
        }
        all
    }

    /// **Upstream:** `(*Olmo3Parser).eat`.
    fn eat(&mut self) -> (Vec<Event>, bool) {
        if self.buffer.is_empty() {
            return (Vec::new(), false);
        }

        match self.state {
            State::Content => {
                if let Some(idx) = self.buffer.find(FUNC_CALLS_OPEN_TAG) {
                    let content = self.buffer[..idx].to_string();
                    let remaining = self.buffer[idx + FUNC_CALLS_OPEN_TAG.len()..].to_string();
                    self.buffer = remaining;
                    self.state = State::ToolCalls;
                    let mut events = Vec::new();
                    if !content.is_empty() {
                        events.push(Event::Content(content));
                    }
                    return (events, true);
                }

                let overlap_len = overlap(&self.buffer, FUNC_CALLS_OPEN_TAG);
                if overlap_len > 0 {
                    // Hold back exactly the ambiguous tail, emit the rest.
                    //
                    // NOTE, and this is a real difference from the qwen
                    // families: upstream does **not** widen the held-back
                    // region over trailing whitespace here, so we must not call
                    // `emit_unambiguous` (which does). Olmo 3 puts
                    // `<function_calls>` straight after prose with no framing
                    // whitespace convention, so the space in front of it is the
                    // user's content and eating it would be a visible bug.
                    let split = self.buffer.len() - overlap_len;
                    let (unambiguous, ambiguous) = super::chop(&self.buffer, split);
                    let (unambiguous, ambiguous) = (unambiguous.to_string(), ambiguous.to_string());
                    self.buffer = ambiguous;
                    let mut events = Vec::new();
                    if !unambiguous.is_empty() {
                        events.push(Event::Content(unambiguous));
                    }
                    return (events, false);
                }

                // Nothing tag-shaped in sight: all of it is content.
                let content = std::mem::take(&mut self.buffer);
                (vec![Event::Content(content)], false)
            }

            State::ToolCalls => {
                let Some(idx) = self.buffer.find(FUNC_CALLS_CLOSE_TAG) else {
                    // Still collecting the body. Nothing can be emitted early --
                    // a half-written `get_weather(location="S` is not a call yet.
                    return (Vec::new(), false);
                };
                let tool_calls_str = self.buffer[..idx].to_string();
                let remaining = self.buffer[idx + FUNC_CALLS_CLOSE_TAG.len()..].to_string();
                self.buffer = remaining;
                self.state = State::ToolCallsDone;

                // **Upstream swallows the error here** (it only trace-logs), so
                // a malformed body yields no calls rather than failing the
                // generation. Kept: olmo3 emits several calls in one block, and
                // upstream's judgment is that losing the block beats killing a
                // reply that may already have useful content in it.
                match parse_function_calls(&tool_calls_str) {
                    Ok(calls) if !calls.is_empty() => (vec![Event::ToolCalls(calls)], true),
                    _ => (Vec::new(), true),
                }
            }

            State::ToolCallsDone => {
                let content = std::mem::take(&mut self.buffer);
                self.state = State::Content;
                if content.is_empty() {
                    return (Vec::new(), false);
                }
                (vec![Event::Content(content)], false)
            }
        }
    }
}

impl Parser for Olmo3Parser {
    /// **Upstream:** `(*Olmo3Parser).Init`. Tools pass straight through -- olmo3
    /// does not rename anything.
    fn init(
        &mut self,
        tools: Vec<Tool>,
        _last_message: Option<&Message>,
        _think: Option<&ThinkValue>,
    ) -> Vec<Tool> {
        self.state = State::Content;
        self.call_index = 0;
        // Upstream does not clear the buffer in Init. We do, because a stale
        // buffer with a fresh state is a bug waiting to happen and upstream only
        // gets away with it by always constructing a fresh parser. Stated as a
        // divergence; it cannot change behaviour for any caller that follows the
        // documented init-then-add lifecycle.
        self.buffer.clear();
        tools
    }

    /// **Upstream:** `(*Olmo3Parser).Add`. See the module docs -- the `done`
    /// branch returns **before** any parsing happens, so it is a drain only.
    fn add(&mut self, s: &str, done: bool) -> Result<Parsed, ParserError> {
        self.buffer.push_str(s);

        if done {
            let buf = std::mem::take(&mut self.buffer);
            if self.state == State::Content && !buf.is_empty() {
                return Ok(Parsed {
                    content: buf,
                    ..Default::default()
                });
            }
            // Mid-tool-call at `done` means the model stopped before closing
            // `</function_calls>`. The half-written body is dropped, not
            // guessed at. Upstream does the same.
            return Ok(Parsed::default());
        }

        let mut out = Parsed::default();
        for event in self.parse_events() {
            match event {
                Event::Content(c) => out.content.push_str(&c),
                Event::ToolCalls(calls) => out.calls.extend(calls),
            }
        }

        for call in &mut out.calls {
            call.function.index = self.call_index;
            self.call_index += 1;
        }

        Ok(out)
    }

    fn preserved_tokens(&self) -> Vec<&'static str> {
        vec![FUNC_CALLS_OPEN_TAG, FUNC_CALLS_CLOSE_TAG]
    }

    fn has_tool_support(&self) -> bool {
        true
    }

    fn has_thinking_support(&self) -> bool {
        false
    }
}

// ===========================================================================
// olmo3-think -- thinking, no tools.
// ===========================================================================

/// **Upstream:** `olmo3ThinkParserState`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
enum ThinkState {
    #[default]
    CollectingThink,
    CollectingContent,
}

/// The `olmo3-think` parser. **Upstream:** `Olmo3ThinkParser`.
///
/// No tool support at all -- [`has_tool_support`](Parser::has_tool_support) is
/// `false`, so a `<function_calls>` block from this model would come out as
/// plain content. That is upstream's shape, not an omission in this port.
#[derive(Debug, Default)]
pub struct Olmo3ThinkParser {
    state: ThinkState,
    buffer: String,
}

impl Olmo3ThinkParser {
    /// **Upstream:** `setInitialState`.
    ///
    /// The model **always thinks first**, because the prompt template injects
    /// the opening `<think>` itself. The single exception is an assistant
    /// prefill *with content*: the caller already started the visible reply, so
    /// thinking is over before generation begins.
    ///
    /// Note it checks `Role == "assistant"` and `Content != ""` -- a prefill
    /// carrying only `thinking` still starts in thinking mode, which is right:
    /// the model is continuing that thought.
    fn set_initial_state(&mut self, last_message: Option<&Message>) {
        let prefill = last_message.is_some_and(|m| m.role == "assistant");
        if prefill && last_message.is_some_and(|m| !m.content.is_empty()) {
            self.state = ThinkState::CollectingContent;
            return;
        }
        self.state = ThinkState::CollectingThink;
    }

    /// **Upstream:** `(*Olmo3ThinkParser).parseEvents`.
    fn parse_events(&mut self) -> Vec<ThinkEvent> {
        let mut all = Vec::new();
        let mut keep_looping = true;
        while keep_looping {
            let (events, again) = self.eat();
            keep_looping = again;
            all.extend(events);
        }
        all
    }

    /// **Upstream:** `(*Olmo3ThinkParser).eat`.
    fn eat(&mut self) -> (Vec<ThinkEvent>, bool) {
        if self.buffer.is_empty() {
            return (Vec::new(), false);
        }

        match self.state {
            ThinkState::CollectingThink => {
                if let Some(idx) = self.buffer.find(THINK_CLOSE_TAG) {
                    let thinking = self.buffer[..idx].trim_end().to_string();
                    let remaining = self.buffer[idx + THINK_CLOSE_TAG.len()..]
                        .trim_start()
                        .to_string();
                    self.buffer = remaining;
                    self.state = ThinkState::CollectingContent;
                    let mut events = Vec::new();
                    if !thinking.is_empty() {
                        events.push(ThinkEvent::Thinking(thinking));
                    }
                    return (events, true);
                }

                // Unlike `Olmo3Parser` above, this one DOES widen the held-back
                // region over trailing whitespace -- because `</think>` is
                // framing and the whitespace in front of it gets trimmed if the
                // tag arrives. Emit that whitespace early and you can never take
                // it back. Same shape as `emit_unambiguous`, spelled out because
                // the two olmo3 parsers deliberately differ here.
                let overlap_len = overlap(&self.buffer, THINK_CLOSE_TAG);
                let split = self.buffer.len() - overlap_len;
                let (before_partial_tag, _) = super::chop(&self.buffer, split);
                let ambiguous_start =
                    before_partial_tag.len() - trailing_whitespace_len(before_partial_tag);
                let (unambiguous, ambiguous) = super::chop(&self.buffer, ambiguous_start);
                let (unambiguous, ambiguous) = (unambiguous.to_string(), ambiguous.to_string());
                self.buffer = ambiguous;
                let mut events = Vec::new();
                if !unambiguous.is_empty() {
                    events.push(ThinkEvent::Thinking(unambiguous));
                }
                (events, false)
            }

            ThinkState::CollectingContent => {
                let content = std::mem::take(&mut self.buffer);
                (vec![ThinkEvent::Content(content)], false)
            }
        }
    }
}

/// **Upstream:** `olmo3Event`.
#[derive(Debug, Clone, PartialEq)]
enum ThinkEvent {
    Thinking(String),
    Content(String),
}

impl Parser for Olmo3ThinkParser {
    fn init(
        &mut self,
        tools: Vec<Tool>,
        last_message: Option<&Message>,
        _think: Option<&ThinkValue>,
    ) -> Vec<Tool> {
        self.set_initial_state(last_message);
        self.buffer.clear();
        tools
    }

    /// **Upstream:** `(*Olmo3ThinkParser).Add`. Note `done` is **ignored** here
    /// -- there is nothing that only drains at the end, because every state
    /// already emits whatever it can on every call. The only thing ever held
    /// back is an ambiguous partial `</think>`, and a stream that ends mid-tag
    /// never had a closing tag to honour anyway.
    fn add(&mut self, s: &str, _done: bool) -> Result<Parsed, ParserError> {
        self.buffer.push_str(s);
        let mut out = Parsed::default();
        for event in self.parse_events() {
            match event {
                ThinkEvent::Thinking(t) => out.thinking.push_str(&t),
                ThinkEvent::Content(c) => out.content.push_str(&c),
            }
        }
        Ok(out)
    }

    fn preserved_tokens(&self) -> Vec<&'static str> {
        vec![THINK_CLOSE_TAG]
    }

    fn has_tool_support(&self) -> bool {
        false
    }

    fn has_thinking_support(&self) -> bool {
        true
    }
}

// ===========================================================================
// The Python-literal call parser.
// ===========================================================================

/// Parse a whole `<function_calls>` body: one call per line.
///
/// **Upstream:** `parseOlmo3FunctionCalls`. Blank lines are skipped; a body that
/// is entirely whitespace yields no calls and no error.
///
/// **Newlines are the separator, full stop.** A single call may therefore not
/// span lines -- upstream splits on `\n` before parsing, so a pretty-printed
/// multi-line dict argument would break. That is a real limitation of the
/// format, not of this port.
fn parse_function_calls(s: &str) -> Result<Vec<ToolCall>, ParserError> {
    let mut calls = Vec::new();
    let s = s.trim();
    if s.is_empty() {
        return Ok(calls);
    }

    for line in s.split('\n') {
        let line = line.trim();
        if line.is_empty() {
            continue;
        }
        calls.push(parse_single_function_call(line)?);
    }

    Ok(calls)
}

/// Parse one `name(args)` line.
///
/// **Upstream:** `parseOlmo3SingleFunctionCall` plus its
/// `regexp.MustCompile(`^(\w+)\((.*)\)$`)`.
///
/// Hand-rolled rather than pulling in `regex`, and it is **exactly** equivalent
/// for this pattern, not an approximation:
///
/// * the whole line must end in `)` (the regex is anchored `$`);
/// * `\w+` cannot contain `(`, so the **first** `(` is where the name ends;
/// * `(.*)` is greedy and `$`-anchored, so the arguments run to the **last**
///   `)`, which is what makes a nested call like `f(g(x))` come out as name `f`,
///   args `g(x)`;
/// * `\w` in Go's RE2 is `[0-9A-Za-z_]` -- ASCII only. So a Unicode function
///   name does **not** match and is rejected, same as upstream.
fn parse_single_function_call(s: &str) -> Result<ToolCall, ParserError> {
    let invalid = || ParserError::MalformedToolCall(format!("invalid function call format: {s}"));

    let rest = s.strip_suffix(')').ok_or_else(invalid)?;
    let open = rest.find('(').ok_or_else(invalid)?;
    let (func_name, args_str) = (&rest[..open], &rest[open + 1..]);

    if func_name.is_empty() || !func_name.bytes().all(|b| b.is_ascii_alphanumeric() || b == b'_') {
        return Err(invalid());
    }

    Ok(ToolCall {
        function: ToolCallFunction {
            name: func_name.to_string(),
            arguments: parse_arguments(args_str)?,
            ..Default::default()
        },
        ..Default::default()
    })
}

/// Parse `key=value, key=value` into ordered arguments.
///
/// **Upstream:** `parseOlmo3Arguments`. Splits on the **first** `=` in each
/// part, so `expr="a=b"` keeps `a=b` as the value.
fn parse_arguments(s: &str) -> Result<ToolCallArguments, ParserError> {
    let mut args = ToolCallArguments::new();
    let s = s.trim();
    if s.is_empty() {
        return Ok(args);
    }

    for part in split_arguments(s) {
        let part = part.trim();
        if part.is_empty() {
            continue;
        }
        let eq = part
            .find('=')
            .ok_or_else(|| ParserError::MalformedToolCall(format!("invalid argument format: {part}")))?;
        let key = part[..eq].trim();
        let value_str = part[eq + 1..].trim();
        args.set(key, parse_value(value_str));
    }

    Ok(args)
}

/// Split on commas that are **not** inside quotes or nested brackets.
///
/// **Upstream:** `splitArguments`. This is why `f(items=["a,b"], n=1)` splits
/// into two parts and not three -- a naive `split(',')` mangles every list and
/// every string containing a comma.
///
/// **Divergence, and why it is safe:** upstream walks raw *bytes*; we walk
/// `char`s. Every character it treats specially (`\`, `"`, `'`, brackets, comma)
/// is ASCII, and a UTF-8 continuation byte can never equal an ASCII byte, so a
/// multi-byte character always lands in the same `default` branch either way.
/// Identical output, minus the risk of slicing mid-character.
///
/// The escape handling is upstream's exactly: a backslash only escapes **inside
/// a string**, and the backslash itself is kept in the output for
/// [`unescape_string`] to deal with later.
fn split_arguments(s: &str) -> Vec<String> {
    let mut parts = Vec::new();
    let mut current = String::new();
    let mut depth: i32 = 0;
    let mut in_string = false;
    let mut string_char = '\0';
    let mut escaped = false;

    for c in s.chars() {
        if escaped {
            current.push(c);
            escaped = false;
            continue;
        }

        if c == '\\' && in_string {
            current.push(c);
            escaped = true;
            continue;
        }

        if (c == '"' || c == '\'') && !in_string {
            in_string = true;
            string_char = c;
            current.push(c);
            continue;
        }

        if c == string_char && in_string {
            in_string = false;
            string_char = '\0';
            current.push(c);
            continue;
        }

        if !in_string {
            match c {
                '(' | '[' | '{' => {
                    depth += 1;
                    current.push(c);
                }
                ')' | ']' | '}' => {
                    depth -= 1;
                    current.push(c);
                }
                ',' if depth == 0 => {
                    parts.push(std::mem::take(&mut current));
                }
                _ => current.push(c),
            }
        } else {
            current.push(c);
        }
    }

    if !current.is_empty() {
        parts.push(current);
    }

    parts
}

/// Parse one Python-ish literal.
///
/// **Upstream:** `parseOlmo3Value`. The order of the checks is load-bearing and
/// is upstream's:
///
/// 1. quoted string (either quote style) -- checked first so `"123"` stays the
///    **string** `"123"` and does not become the number `123`;
/// 2. `true`/`True`, `false`/`False` -- both casings, because the model may emit
///    Python or JSON spelling;
/// 3. `null`/`None`/`nil`;
/// 4. integer, then float -- integer first so `72` is an integer and not `72.0`;
/// 5. `[...]` list, `{...}` dict;
/// 6. **anything else falls back to a bare string**, unquoted. So a stray
///    `location=SF` yields `"SF"` rather than an error. Lenient on purpose:
///    upstream would rather make the call than drop it.
///
/// **Never returns an error** -- upstream's signature has one but no branch ever
/// populates it (the recursive list/dict cases only forward their own, which are
/// likewise unreachable). Dropped rather than ported as an `Err` that cannot
/// happen.
///
/// A dict's keys land in a `serde_json::Map`. Upstream uses Go's `map[string]any`,
/// which has **no** order at all, so nothing observable is lost -- unlike the
/// top-level [`ToolCallArguments`], where insertion order genuinely matters.
fn parse_value(s: &str) -> serde_json::Value {
    use serde_json::Value;

    let s = s.trim();

    // Quoted string. Note `len() >= 2` guards the degenerate `"` (one byte),
    // which would otherwise both start and end the string.
    if s.len() >= 2
        && ((s.starts_with('"') && s.ends_with('"')) || (s.starts_with('\'') && s.ends_with('\'')))
    {
        return Value::String(unescape_string(&s[1..s.len() - 1]));
    }

    if s == "true" || s == "True" {
        return Value::Bool(true);
    }
    if s == "false" || s == "False" {
        return Value::Bool(false);
    }
    if s == "null" || s == "None" || s == "nil" {
        return Value::Null;
    }

    if let Ok(i) = s.parse::<i64>() {
        return Value::Number(i.into());
    }
    if let Ok(f) = s.parse::<f64>()
        && let Some(n) = serde_json::Number::from_f64(f)
    {
        return Value::Number(n);
    }

    if let Some(inner) = s.strip_prefix('[').and_then(|x| x.strip_suffix(']')) {
        let inner = inner.trim();
        if inner.is_empty() {
            return Value::Array(Vec::new());
        }
        return Value::Array(split_arguments(inner).iter().map(|p| parse_value(p)).collect());
    }

    if let Some(inner) = s.strip_prefix('{').and_then(|x| x.strip_suffix('}')) {
        return parse_object(inner);
    }

    // Bare, unquoted -- keep it as a string.
    Value::String(s.to_string())
}

/// Parse a `{...}` body: `key: value` pairs, keys optionally quoted.
///
/// **Upstream:** `parseOlmo3Object`. Note the separator is `:` (dict syntax),
/// not `=` (call syntax) -- mixing the two up is the easy mistake here.
///
/// A malformed entry (no `:`) is **skipped**, where upstream returns an error
/// that its only caller then swallows into a bare-string fallback. Same
/// observable result for the entry, and it keeps the sibling keys that did
/// parse. Stated because it is a divergence in the code shape, not the outcome.
fn parse_object(s: &str) -> serde_json::Value {
    let s = s.trim();
    let mut obj = serde_json::Map::new();
    if s.is_empty() {
        return serde_json::Value::Object(obj);
    }

    for part in split_arguments(s) {
        let part = part.trim();
        if part.is_empty() {
            continue;
        }
        let Some(colon) = part.find(':') else {
            continue;
        };
        let mut key = part[..colon].trim();
        let value_str = part[colon + 1..].trim();

        if key.len() >= 2
            && ((key.starts_with('"') && key.ends_with('"'))
                || (key.starts_with('\'') && key.ends_with('\'')))
        {
            key = &key[1..key.len() - 1];
        }

        obj.insert(key.to_string(), parse_value(value_str));
    }

    serde_json::Value::Object(obj)
}

/// Undo the escapes olmo 3 uses inside a quoted argument.
///
/// **Upstream:** `unescapeString`, including its **NUL-placeholder trick**:
/// `\\` is first swapped for a literal `\0`, the other escapes are then
/// expanded, and finally `\0` becomes a single backslash.
///
/// The trick is not decoration -- it is what stops `\\n` (an escaped backslash
/// followed by the letter `n`) from being mangled into a newline. Rewrite this
/// as five independent `replace` calls and that case silently breaks.
///
/// **What would make this wrong:** an argument that genuinely contains a NUL
/// byte would be corrupted, since the placeholder collides with it. That is
/// upstream's bug and it is carried faithfully; a tool argument containing a raw
/// NUL is not a thing any model emits, and diverging here would mean this port
/// and ollama disagree on a real input.
fn unescape_string(s: &str) -> String {
    const PLACEHOLDER: &str = "\u{0}";
    let s = s.replace("\\\\", PLACEHOLDER);
    let s = s.replace("\\\"", "\"");
    let s = s.replace("\\'", "'");
    let s = s.replace("\\n", "\n");
    let s = s.replace("\\t", "\t");
    let s = s.replace("\\r", "\r");
    s.replace(PLACEHOLDER, "\\")
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    fn olmo3() -> Olmo3Parser {
        let mut p = Olmo3Parser::default();
        p.init(Vec::new(), None, None);
        p
    }

    /// Upstream's own harness: feed the body with `done = false`, then drain
    /// with `add("", true)`. See the module docs for why that order is required.
    fn run(p: &mut Olmo3Parser, input: &str) -> Parsed {
        let mut got = p.add(input, false).expect("add");
        let drained = p.add("", true).expect("drain");
        got.content.push_str(&drained.content);
        got.thinking.push_str(&drained.thinking);
        got.calls.extend(drained.calls);
        got
    }

    /// Upstream `TestOlmo3Parser`, ported verbatim as ground truth.
    #[test]
    fn olmo3_splits_content_from_python_style_tool_calls() {
        let mut p = olmo3();
        let got = run(&mut p, "Hello, how can I help you?");
        assert_eq!(got.content, "Hello, how can I help you?");
        assert!(got.calls.is_empty());

        let mut p = olmo3();
        let got = run(
            &mut p,
            r#"<function_calls>get_weather(location="San Francisco")</function_calls>"#,
        );
        assert!(got.content.is_empty());
        assert_eq!(got.calls.len(), 1);
        assert_eq!(got.calls[0].function.name, "get_weather");
        assert_eq!(
            got.calls[0].function.arguments.get("location"),
            Some(&json!("San Francisco"))
        );

        let mut p = olmo3();
        let got = run(
            &mut p,
            r#"Let me check the weather.<function_calls>get_weather(location="NYC")</function_calls>"#,
        );
        assert_eq!(got.content, "Let me check the weather.");
        assert_eq!(got.calls.len(), 1);
    }

    #[test]
    fn olmo3_handles_every_argument_type_upstream_pins() {
        // (input, function name, key, expected value)
        let cases: Vec<(&str, &str, &str, serde_json::Value)> = vec![
            (
                r#"<function_calls>set_temperature(value=72)</function_calls>"#,
                "set_temperature",
                "value",
                json!(72),
            ),
            (
                r#"<function_calls>set_price(amount=19.99)</function_calls>"#,
                "set_price",
                "amount",
                json!(19.99),
            ),
            (
                r#"<function_calls>toggle_setting(enabled=true)</function_calls>"#,
                "toggle_setting",
                "enabled",
                json!(true),
            ),
            (
                r#"<function_calls>clear_value(field=null)</function_calls>"#,
                "clear_value",
                "field",
                json!(null),
            ),
            (
                r#"<function_calls>process_items(items=["apple", "banana", "cherry"])</function_calls>"#,
                "process_items",
                "items",
                json!(["apple", "banana", "cherry"]),
            ),
            (
                r#"<function_calls>update_config(settings={"theme": "dark", "fontSize": 14})</function_calls>"#,
                "update_config",
                "settings",
                json!({"theme": "dark", "fontSize": 14}),
            ),
            (
                r#"<function_calls>create_request(data={"user": {"name": "John", "age": 30}, "active": true})</function_calls>"#,
                "create_request",
                "data",
                json!({"user": {"name": "John", "age": 30}, "active": true}),
            ),
            (
                r#"<function_calls>search(query='hello world')</function_calls>"#,
                "search",
                "query",
                json!("hello world"),
            ),
            (
                r#"<function_calls>search(query="say \"hello\"")</function_calls>"#,
                "search",
                "query",
                json!(r#"say "hello""#),
            ),
        ];

        for (input, name, key, want) in cases {
            let mut p = olmo3();
            let got = run(&mut p, input);
            assert_eq!(got.calls.len(), 1, "for {input}");
            assert_eq!(got.calls[0].function.name, name, "for {input}");
            assert_eq!(got.calls[0].function.arguments.get(key), Some(&want), "for {input}");
        }
    }

    #[test]
    fn a_call_with_no_arguments_yields_an_empty_argument_map() {
        let mut p = olmo3();
        let got = run(&mut p, "<function_calls>get_current_time()</function_calls>");
        assert_eq!(got.calls.len(), 1);
        assert_eq!(got.calls[0].function.name, "get_current_time");
        assert!(got.calls[0].function.arguments.is_empty());
    }

    /// One call per line, and the running index numbers them across the stream.
    #[test]
    fn multiple_calls_on_separate_lines_are_numbered_in_order() {
        let mut p = olmo3();
        let got = run(
            &mut p,
            "<function_calls>get_weather(location=\"San Francisco\")\nget_weather(location=\"New York\")</function_calls>",
        );
        assert_eq!(got.calls.len(), 2);
        assert_eq!(got.calls[0].function.index, 0);
        assert_eq!(got.calls[1].function.index, 1);
        assert_eq!(
            got.calls[1].function.arguments.get("location"),
            Some(&json!("New York"))
        );
    }

    #[test]
    fn arguments_keep_the_order_the_model_wrote_them() {
        let mut p = olmo3();
        let got = run(
            &mut p,
            r#"<function_calls>book_flight(from="SFO", to="NYC", date="2024-01-15")</function_calls>"#,
        );
        let keys: Vec<&str> = got.calls[0]
            .function
            .arguments
            .0
            .keys()
            .map(String::as_str)
            .collect();
        assert_eq!(keys, ["from", "to", "date"]);
    }

    /// Upstream `TestOlmo3Parser_Streaming`.
    #[test]
    fn olmo3_survives_the_open_tag_being_split_across_chunks() {
        let cases: Vec<(Vec<&str>, &str, usize)> = vec![
            (vec!["Hello, ", "how ", "can I help?"], "Hello, how can I help?", 0),
            (
                vec!["<function_", "calls>get_weather", "(location=\"SF\")", "</function_calls>"],
                "",
                1,
            ),
            (
                vec!["Let me check.", "<function_calls>", "get_weather(location=\"NYC\")", "</function_calls>"],
                "Let me check.",
                1,
            ),
            (vec!["<func", "tion_calls>test()</function_calls>"], "", 1),
        ];

        for (chunks, want_content, want_calls) in cases {
            let mut p = olmo3();
            let mut content = String::new();
            let mut calls = Vec::new();
            for chunk in &chunks {
                let got = p.add(chunk, false).expect("add");
                content.push_str(&got.content);
                calls.extend(got.calls);
            }
            let got = p.add("", true).expect("drain");
            content.push_str(&got.content);
            calls.extend(got.calls);

            assert_eq!(content, want_content, "for {chunks:?}");
            assert_eq!(calls.len(), want_calls, "for {chunks:?}");
        }
    }

    /// One byte at a time must agree with one big chunk.
    #[test]
    fn olmo3_fed_one_byte_at_a_time_gives_the_same_answer() {
        let input = "Checking now.<function_calls>get_weather(location=\"SG\")</function_calls>All done.";

        let mut whole = olmo3();
        let want = run(&mut whole, input);

        let mut p = olmo3();
        let mut got = Parsed::default();
        for (i, ch) in input.char_indices() {
            let part = p.add(&input[i..i + ch.len_utf8()], false).expect("add");
            got.content.push_str(&part.content);
            got.calls.extend(part.calls);
        }
        let drained = p.add("", true).expect("drain");
        got.content.push_str(&drained.content);
        got.calls.extend(drained.calls);

        assert_eq!(got.content, want.content);
        assert_eq!(got.content, "Checking now.All done.");
        assert_eq!(got.calls.len(), want.calls.len());
        assert_eq!(got.calls.len(), 1);
    }

    /// Upstream `TestParseOlmo3FunctionCalls`.
    #[test]
    fn a_whitespace_only_call_body_yields_no_calls_and_no_error() {
        assert!(parse_function_calls("").expect("parse").is_empty());
        assert!(parse_function_calls("   \n   ").expect("parse").is_empty());
    }

    /// Upstream `TestParseOlmo3Value`, ported verbatim as ground truth.
    ///
    /// `approx_constant` is allowed because upstream's float fixture is
    /// literally `3.14` and clippy reads that as a botched `PI`. It is a test
    /// input, not a mathematical constant -- swapping in `std::f64::consts::PI`
    /// would stop testing what upstream tests.
    #[expect(clippy::approx_constant)]
    #[test]
    fn python_literals_parse_to_the_right_json_values() {
        let cases: Vec<(&str, serde_json::Value)> = vec![
            (r#""hello""#, json!("hello")),
            (r#"'hello'"#, json!("hello")),
            ("42", json!(42)),
            ("-10", json!(-10)),
            ("3.14", json!(3.14)),
            ("true", json!(true)),
            ("True", json!(true)),
            ("false", json!(false)),
            ("null", json!(null)),
            ("None", json!(null)),
            ("[]", json!([])),
            (r#"["a", "b"]"#, json!(["a", "b"])),
            ("[1, 2, 3]", json!([1, 2, 3])),
            ("{}", json!({})),
            (r#"{"name": "John"}"#, json!({"name": "John"})),
            (r#"{"age": 30}"#, json!({"age": 30})),
            (r#"{"a": 1, "b": 2}"#, json!({"a": 1, "b": 2})),
        ];
        for (input, want) in cases {
            assert_eq!(parse_value(input), want, "for {input}");
        }
    }

    /// The NUL-placeholder trick, tested for the case it exists to protect: an
    /// escaped backslash immediately followed by `n` must NOT become a newline.
    #[test]
    fn an_escaped_backslash_before_an_n_does_not_become_a_newline() {
        assert_eq!(unescape_string(r"a\\nb"), "a\\nb");
        assert_eq!(unescape_string(r"a\nb"), "a\nb");
        assert_eq!(unescape_string(r#"say \"hi\""#), r#"say "hi""#);
    }

    /// A comma inside a string or a bracket must not split the arguments.
    #[test]
    fn commas_inside_strings_and_brackets_do_not_split_arguments() {
        let args = parse_arguments(r#"items=["a,b", "c"], note="x, y", n=1"#).expect("parse");
        assert_eq!(args.len(), 3);
        assert_eq!(args.get("items"), Some(&json!(["a,b", "c"])));
        assert_eq!(args.get("note"), Some(&json!("x, y")));
        assert_eq!(args.get("n"), Some(&json!(1)));
    }

    #[test]
    fn a_line_that_is_not_a_function_call_is_rejected() {
        assert!(parse_single_function_call("not a call").is_err());
        assert!(parse_single_function_call("has spaces(x=1)").is_err());
        assert!(parse_single_function_call("f(x=1").is_err());
    }

    /// A malformed body loses the calls but must NOT kill the reply -- upstream
    /// only trace-logs the error.
    #[test]
    fn a_malformed_tool_call_body_is_dropped_rather_than_failing_the_generation() {
        let mut p = olmo3();
        let got = run(&mut p, "text<function_calls>this is not a call</function_calls>tail");
        assert!(got.calls.is_empty());
        assert_eq!(got.content, "texttail");
    }

    #[test]
    fn olmo3_advertises_its_tags_and_its_capabilities() {
        let p = olmo3();
        assert_eq!(
            p.preserved_tokens(),
            vec!["<function_calls>", "</function_calls>"]
        );
        assert!(p.has_tool_support());
        assert!(!p.has_thinking_support());
    }

    // --- olmo3-think ------------------------------------------------------

    fn olmo3_think() -> Olmo3ThinkParser {
        let mut p = Olmo3ThinkParser::default();
        p.init(Vec::new(), None, None);
        p
    }

    /// The model always starts inside `<think>` -- the prompt opened it.
    #[test]
    fn olmo3_think_starts_in_thinking_mode_with_no_opening_tag() {
        let mut p = olmo3_think();
        let got = p.add("reasoning away</think>the answer", true).expect("add");
        assert_eq!(got.thinking, "reasoning away");
        assert_eq!(got.content, "the answer");
        assert!(got.calls.is_empty());
    }

    #[test]
    fn olmo3_think_trims_the_whitespace_framing_the_close_tag() {
        let mut p = olmo3_think();
        let got = p.add("reasoning   \n</think>\n\n  the answer", true).expect("add");
        assert_eq!(got.thinking, "reasoning");
        assert_eq!(got.content, "the answer");
    }

    /// A prefill with visible content means the reply already started, so there
    /// is no thinking block left to close.
    #[test]
    fn an_assistant_content_prefill_starts_olmo3_think_in_content_mode() {
        let mut p = Olmo3ThinkParser::default();
        let last = Message::new("assistant", "Sure:");
        p.init(Vec::new(), Some(&last), None);
        let got = p.add(" here you go", true).expect("add");
        assert_eq!(got.content, " here you go");
        assert!(got.thinking.is_empty());
    }

    /// A prefill carrying only `thinking` is the model CONTINUING that thought,
    /// so it stays in thinking mode.
    #[test]
    fn a_thinking_only_prefill_keeps_olmo3_think_in_thinking_mode() {
        let mut p = Olmo3ThinkParser::default();
        let last = Message {
            role: "assistant".into(),
            thinking: "so far".into(),
            ..Default::default()
        };
        p.init(Vec::new(), Some(&last), None);
        let got = p.add(" and also</think>done", true).expect("add");
        assert_eq!(got.thinking, " and also");
        assert_eq!(got.content, "done");
    }

    #[test]
    fn a_close_tag_split_across_chunks_never_leaks_into_thinking() {
        let mut p = olmo3_think();
        let a = p.add("thought</thi", false).expect("add");
        assert_eq!(a.thinking, "thought");
        assert!(a.content.is_empty());
        let b = p.add("nk>visible", true).expect("add");
        assert!(b.thinking.is_empty());
        assert_eq!(b.content, "visible");
    }

    #[test]
    fn olmo3_think_fed_one_byte_at_a_time_gives_the_same_answer() {
        let input = "let me work it out</think>The answer is 4.";

        let mut whole = olmo3_think();
        let want = whole.add(input, true).expect("add");

        let mut p = olmo3_think();
        let mut got = Parsed::default();
        for (i, ch) in input.char_indices() {
            let part = p
                .add(&input[i..i + ch.len_utf8()], i + ch.len_utf8() == input.len())
                .expect("add");
            got.content.push_str(&part.content);
            got.thinking.push_str(&part.thinking);
        }

        assert_eq!(got.thinking, want.thinking);
        assert_eq!(got.content, want.content);
        assert_eq!(got.thinking, "let me work it out");
        assert_eq!(got.content, "The answer is 4.");
    }

    #[test]
    fn olmo3_think_advertises_thinking_but_not_tools() {
        let p = olmo3_think();
        assert_eq!(p.preserved_tokens(), vec!["</think>"]);
        assert!(!p.has_tool_support());
        assert!(p.has_thinking_support());
    }
}
