pub const CONFIG_DIR_VAR: &str = "BD_CONFIG_DIR";
pub const NO_AUTO_UPGRADE_VAR: &str = "BD_NO_AUTO_UPGRADE";
pub const ACTOR_VAR: &str = "BD_ACTOR";
pub const REPL_LISTEN_ADDR_VAR: &str = "BD_REPL_LISTEN_ADDR";
pub const REPL_MAX_CONNECTIONS_VAR: &str = "BD_REPL_MAX_CONNECTIONS";
pub const LOG_STDOUT_VAR: &str = "BD_LOG_STDOUT";
pub const LOG_STDOUT_FORMAT_VAR: &str = "BD_LOG_STDOUT_FORMAT";
pub const LOG_FILTER_VAR: &str = "BD_LOG_FILTER";
pub const LOG_FILE_VAR: &str = "BD_LOG_FILE";
pub const LOG_DIR_VAR: &str = "BD_LOG_DIR";
pub const LOG_FILE_FORMAT_VAR: &str = "BD_LOG_FILE_FORMAT";
pub const LOG_ROTATION_VAR: &str = "BD_LOG_ROTATION";
pub const LOG_RETENTION_DAYS_VAR: &str = "BD_LOG_RETENTION_DAYS";
pub const LOG_RETENTION_FILES_VAR: &str = "BD_LOG_RETENTION_FILES";
pub const DATA_DIR_VAR: &str = "BD_DATA_DIR";
pub const RUNTIME_DIR_VAR: &str = "BD_RUNTIME_DIR";
pub const TEST_FAST_VAR: &str = "BD_TEST_FAST";

pub const ENV_OVERRIDE_KEYS: &[&str] = &[
    NO_AUTO_UPGRADE_VAR,
    ACTOR_VAR,
    REPL_LISTEN_ADDR_VAR,
    REPL_MAX_CONNECTIONS_VAR,
    LOG_STDOUT_VAR,
    LOG_STDOUT_FORMAT_VAR,
    LOG_FILTER_VAR,
    LOG_FILE_VAR,
    LOG_DIR_VAR,
    LOG_FILE_FORMAT_VAR,
    LOG_ROTATION_VAR,
    LOG_RETENTION_DAYS_VAR,
    LOG_RETENTION_FILES_VAR,
    DATA_DIR_VAR,
    RUNTIME_DIR_VAR,
    TEST_FAST_VAR,
];

pub const CONFIG_ENV_KEYS: &[&str] = &[
    CONFIG_DIR_VAR,
    NO_AUTO_UPGRADE_VAR,
    ACTOR_VAR,
    REPL_LISTEN_ADDR_VAR,
    REPL_MAX_CONNECTIONS_VAR,
    LOG_STDOUT_VAR,
    LOG_STDOUT_FORMAT_VAR,
    LOG_FILTER_VAR,
    LOG_FILE_VAR,
    LOG_DIR_VAR,
    LOG_FILE_FORMAT_VAR,
    LOG_ROTATION_VAR,
    LOG_RETENTION_DAYS_VAR,
    LOG_RETENTION_FILES_VAR,
    DATA_DIR_VAR,
    RUNTIME_DIR_VAR,
    TEST_FAST_VAR,
];
